# Use root/example as user/password credentials
version: '3.8' # 도커컴포즈 최신버전

services:

  mysql: # 서비스이름으로 편의대로 지을 수 있음
    container_name: mysql_local
    build: .
    ports:
      - "3307:3306" # 내 로컬상 이미 3306포트는 할당되어있어서 3307으로 변경하였음
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul